CLASS /lrn/cl_437h_handle_event DEFINITION PUBLIC
  FINAL CREATE PUBLIC
  FOR EVENTS OF /lrn/437h_r_travel.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS /LRN/CL_437H_HANDLE_EVENT IMPLEMENTATION.
ENDCLASS.
