CLASS /lrn/bp_437h_r_travel DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF /lrn/437h_r_travel.
protected section.
private section.
ENDCLASS.



CLASS /LRN/BP_437H_R_TRAVEL IMPLEMENTATION.
ENDCLASS.
