CLASS /lrn/bp_437e_r_travel DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF /lrn/437e_r_travel.
protected section.
private section.
ENDCLASS.



CLASS /LRN/BP_437E_R_TRAVEL IMPLEMENTATION.
ENDCLASS.
