CLASS /lrn/bp_437b_r_travel DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF /lrn/437b_r_travel.
protected section.
private section.
ENDCLASS.



CLASS /LRN/BP_437B_R_TRAVEL IMPLEMENTATION.
ENDCLASS.
