CLASS /lrn/cl_437g_handler DEFINITION PUBLIC
  FINAL CREATE PUBLIC
  FOR EVENTS OF /lrn/437g_r_travel.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS /LRN/CL_437G_HANDLER IMPLEMENTATION.
ENDCLASS.
