CLASS /lrn/bp_437c_r_travel DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF /lrn/437c_r_travel.
protected section.
private section.
ENDCLASS.



CLASS /LRN/BP_437C_R_TRAVEL IMPLEMENTATION.
ENDCLASS.
